/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Bll.GestionMatricula;
import Chisaguano.Util;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author labctr
 */
public class FrmRegistroCalificaciones extends javax.swing.JInternalFrame {
    private final String titulo= "Registro de Matricula";
    private GestionMatricula matriculaBll = new GestionMatricula();
    
    private boolean Validar(){
        float nota=(float) this.snnValor.getValue();
        if(nota==0.f){
            vtnPrincipal.verMensaje("Calificacion no valida", titulo,JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    private void ConsultarMatricula() throws IOException{
        String numero= this.txtNumeroMatriculas.getText();
        matriculaBll.consultar(numero);
        this.txtDatosMatricula.setText(matriculaBll.Imprimir());
    }
    
    private String Calificar() throws IOException{
        float nota = (float) this.snnValor.getValue();
        String mensaje = matriculaBll.calificar(nota);
        matriculaBll.archivar();
        return mensaje;
    }
    /**
     * Creates new form FrmRegistroCalificaciones
     */
    public FrmRegistroCalificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroCalificaciones = new javax.swing.JLabel();
        lblNumeroMatriculas = new javax.swing.JLabel();
        txtNumeroMatriculas = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        pnlDatosMatricula = new javax.swing.JScrollPane();
        txtDatosMatricula = new javax.swing.JTextArea();
        pnlCalificaciones = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        snnValor = new javax.swing.JSpinner();
        btnguardarcalificaciones = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblRegistroCalificaciones.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblRegistroCalificaciones.setText("Registro de Calificaciones");

        lblNumeroMatriculas.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblNumeroMatriculas.setText("N° Matricula:");

        btnbuscar.setIcon(new javax.swing.ImageIcon("/home/labctr/Documentos/POO/3 parcial/iconos/search.png")); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        txtDatosMatricula.setEditable(false);
        txtDatosMatricula.setColumns(20);
        txtDatosMatricula.setRows(5);
        pnlDatosMatricula.setViewportView(txtDatosMatricula);

        pnlCalificaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Calificaciones"));

        lblValor.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblValor.setText("Valor:");

        snnValor.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), Float.valueOf(20.0f), Float.valueOf(0.01f)));

        btnguardarcalificaciones.setIcon(new javax.swing.ImageIcon("/home/labctr/Documentos/POO/3 parcial/iconos/save.png")); // NOI18N
        btnguardarcalificaciones.setText("Guardar");
        btnguardarcalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarcalificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCalificacionesLayout = new javax.swing.GroupLayout(pnlCalificaciones);
        pnlCalificaciones.setLayout(pnlCalificacionesLayout);
        pnlCalificacionesLayout.setHorizontalGroup(
            pnlCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(snnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnguardarcalificaciones)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        pnlCalificacionesLayout.setVerticalGroup(
            pnlCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCalificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(snnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardarcalificaciones))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumeroMatriculas)
                .addGap(1, 1, 1)
                .addComponent(txtNumeroMatriculas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lblRegistroCalificaciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlDatosMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblRegistroCalificaciones)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeroMatriculas)
                        .addComponent(txtNumeroMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addComponent(pnlDatosMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlCalificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try{
            this.ConsultarMatricula();
        }catch(Exception e){
            Util.imprimir("Error"+e.toString());
            vtnPrincipal.verMensaje("Error al buscar la Matricula",titulo,JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnguardarcalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarcalificacionesActionPerformed
        try{
            if(Validar()){
                String mensaje= this.Calificar();
                vtnPrincipal.verMensaje(mensaje, titulo,JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
            Util.imprimir("Error"+e.toString());
            vtnPrincipal.verMensaje("Error al calificar la Matricula",titulo,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnguardarcalificacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnguardarcalificaciones;
    private javax.swing.JLabel lblNumeroMatriculas;
    private javax.swing.JLabel lblRegistroCalificaciones;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlCalificaciones;
    private javax.swing.JScrollPane pnlDatosMatricula;
    private javax.swing.JSpinner snnValor;
    private javax.swing.JTextArea txtDatosMatricula;
    private javax.swing.JTextField txtNumeroMatriculas;
    // End of variables declaration//GEN-END:variables
}
