/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ui;

import Bll.GestionCurso;
import Bll.GestionMatricula;
import Chisaguano.Util;
import beu.Curso;
import beu.Matricula;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author labctr
 */
public class FrmReporteCalificaciones extends javax.swing.JInternalFrame {
    private final String titulo = "Reporte de Calificaciones";
    private GestionCurso cursoBll = new GestionCurso();
    private GestionMatricula matriculaBll = new GestionMatricula();
    private List<Curso> cursos;
    private List<Matricula> calificaciones;
    private final DefaultTableModel dtmCalificaciones= new DefaultTableModel();
    
    private void leerCursos() throws IOException{
        try{
            Curso ficticio = new Curso("--Seleccione--"," ",0.0f);
            this.cmbCursos.addItem(ficticio);
            cursos = cursoBll.getCursos();
            cursos.forEach((c) ->{
            this.cmbCursos.addItem(c);
            });
        }catch(Exception e){
            Util.imprimir("Error"+e.toString());
            vtnPrincipal.verMensaje("Error al leer los cursos",titulo,JOptionPane.ERROR_MESSAGE);
        }
    }
    private void configurarModeloTabla(){
        String[]columnas={"Nombre","Promedio","Estado"};
        this.dtmCalificaciones.setColumnIdentifiers(columnas);
        this.tblReporteCalificaciones.setModel(dtmCalificaciones);
    }
    
    private void MostrarCalificaciones(){
        //Elimina las filas de la tabla
        int lim = dtmCalificaciones.getRowCount()-1;
        for(int i=lim; i>=0;i--){
            this.dtmCalificaciones.removeRow(i);
        }
        for(Matricula m: calificaciones){
            Vector fila= new Vector();
            fila.addElement(Util.mostrarfecha(m.getFecha()));
            fila.addElement(m.getEstudiante());
            fila.addElement(m.getPromedio());
            fila.addElement(m.getEstado());
            this.dtmCalificaciones.addRow(fila);
        }
        this.tblReporteCalificaciones.setModel(dtmCalificaciones);
    }
     
    private void BuscarMatriculas() throws IOException{
        Curso seleccionado = (Curso)this.cmbCursos.getSelectedItem();
        calificaciones= matriculaBll.reportar(seleccionado.getTitulo()); 
        MostrarCalificaciones();
    }
    
    /**
     * Creates new form FrmReporteCalificaciones
     */
    public FrmReporteCalificaciones() {
        initComponents();
        try {
            leerCursos();
        } catch (IOException ex) {
            Logger.getLogger(FrmRegistroMatricula.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.configurarModeloTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        cmbCursos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReporteCalificaciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Registro de Calificaciones");

        btnbuscar.setIcon(new javax.swing.ImageIcon("/home/labctr/Documentos/POO/3 parcial/iconos/search.png")); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("Curso");

        tblReporteCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblReporteCalificaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnbuscar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try{
            BuscarMatriculas();
        }catch(Exception e){
            Util.imprimir("Error"+e.toString());
            vtnPrincipal.verMensaje("Error al buscar la Matricula",titulo,JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnbuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JComboBox<Curso> cmbCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblReporteCalificaciones;
    // End of variables declaration//GEN-END:variables
}
